---
- hosts: default
  sudo: yes
  tasks:

  - name: ansible prereq | install libselinux-python
    yum: name=libselinux-python state=latest

  - name: ansible prereq | install unzip 
    yum: name=unzip state=latest
